def receipt_page():
    import streamlit as st
    import pandas as pd
    from datetime import date
    import pymysql
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    from io import BytesIO

    st.set_page_config(page_title="Receipts", layout="wide")

    db = pymysql.connect(
        host="localhost",
        user="root",
        password="7770",
        database="odoo"
    )

    cursor = db.cursor()
    def create_pdf(dataframe):

        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=letter)

        width, height = letter

        pdf.setFont("Helvetica-Bold",22)
        pdf.drawCentredString(width/2, height-50, "CoreInventory System")

        pdf.setFont("Helvetica-Bold",16)
        pdf.drawCentredString(width/2, height-80, "Receipt History Report")

        pdf.setFont("Helvetica",10)
        pdf.drawRightString(width-40, height-110, f"Generated: {date.today()}")

        y = height - 150

        columns = ["Receipt ID","Supplier","Product","Qty","Warehouse","Status","Date"]
        x_positions = [40,100,200,330,370,440,510]

        pdf.setFont("Helvetica-Bold",10)

        for i,col in enumerate(columns):
            pdf.drawString(x_positions[i], y, col)

        y -= 10
        pdf.line(40,y,560,y)
        y -= 20

        pdf.setFont("Helvetica",9)

        for index,row in dataframe.iterrows():

            pdf.drawString(x_positions[0], y, str(row["Receipt ID"]))
            pdf.drawString(x_positions[1], y, str(row["Supplier"]))
            pdf.drawString(x_positions[2], y, str(row["Product"]))
            pdf.drawString(x_positions[3], y, str(row["Quantity"]))
            pdf.drawString(x_positions[4], y, str(row["Warehouse"]))
            pdf.drawString(x_positions[5], y, str(row["Status"]))
            pdf.drawString(x_positions[6], y, str(row["Date"]))

            y -= 20

            if y < 50:
                pdf.showPage()
                y = height - 100

        pdf.setFont("Helvetica-Oblique",9)
        pdf.drawCentredString(width/2,30,"Generated by CoreInventory Management System")

        pdf.save()
        buffer.seek(0)

        return buffer

    # ------------------- CSS -------------------

    st.markdown("""
    <style>

    /* Download Receipt Button */
    .stDownloadButton > button {
        background: linear-gradient(45deg,#ff416c,#ff4b2b);
        color: white !important;
        font-size:16px;
        font-weight:600;
        padding:10px 25px;
        border-radius:10px;
        border:none;
        box-shadow:0px 6px 15px rgba(0,0,0,0.4);
        transition: all 0.3s ease;
    }

    /* Hover Effect */
    .stDownloadButton > button:hover {
        background: linear-gradient(45deg,#ff4b2b,#ff416c);
        transform: translateY(-2px);
        box-shadow:0px 10px 25px rgba(0,0,0,0.6);
    }

    /* Active click */
    .stDownloadButton > button:active {
        transform: scale(0.96);
    }

    </style>
    """, unsafe_allow_html=True)

    st.markdown('<p class="title">📥 Incoming Stock Management</p>', unsafe_allow_html=True)

    # ---------------- SESSION DATA ----------------

    if "receipts" not in st.session_state:
        st.session_state.receipts = pd.DataFrame(columns=[
            "Supplier","Product","Category","Quantity","Warehouse","Status","Date"
        ])

    if "stock" not in st.session_state:
        st.session_state.stock = {}

    df = st.session_state.receipts

    # ---------------- KPI CARDS ----------------

    cursor.execute("SELECT COUNT(*) FROM receipts")
    total_receipts = cursor.fetchone()[0]

    cursor.execute("SELECT IFNULL(SUM(quantity),0) FROM receipts")
    total_items = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(DISTINCT supplier_name) FROM receipts")
    suppliers = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(DISTINCT product_id) FROM receipts")
    products_count = cursor.fetchone()[0]

    col1,col2,col3,col4 = st.columns(4)

    with col1:
        st.markdown(f"""
        <div class="card">
        <div class="metric">{total_receipts}</div>
        <div class="label">Receipts</div>
        </div>
        """, unsafe_allow_html=True)

    with col2:
        st.markdown(f"""
        <div class="card">
        <div class="metric">{total_items}</div>
        <div class="label">Items Received</div>
        </div>
        """, unsafe_allow_html=True)

    with col3:
        st.markdown(f"""
        <div class="card">
        <div class="metric">{suppliers}</div>
        <div class="label">Suppliers</div>
        </div>
        """, unsafe_allow_html=True)

    with col4:
        st.markdown(f"""
        <div class="card">
        <div class="metric">{products_count}</div>
        <div class="label">Products</div>
        </div>
        """, unsafe_allow_html=True)

    st.divider()

    # ---------------- SIDEBAR FILTER ----------------

    st.sidebar.title("Filters")

    supplier_filter = st.sidebar.text_input("Supplier")
    product_filter = st.sidebar.text_input("Product")

    filtered_df = df.copy()

    if supplier_filter:
        filtered_df = filtered_df[
            filtered_df["Supplier"].str.contains(supplier_filter,case=False)
        ]

    if product_filter:
        filtered_df = filtered_df[
            filtered_df["Product"].str.contains(product_filter,case=False)
        ]

    # ---------------- TABS ----------------

    tab1,tab2,tab3,tab4 = st.tabs([
    "➕ Create Receipt",
    "📋 Receipt History",
    "📦 Current Stock",
    "📊 Stock Ledger"
    ])

    # ---------------- CREATE RECEIPT ----------------

    with tab1:

        col1,col2,col3 = st.columns(3)

        supplier = col1.text_input("Supplier Name")

        cursor.execute("SELECT product_id, product_name FROM products")
        products = cursor.fetchall()

        product_dict = {name: pid for pid, name in products}

        product = col2.selectbox("Product Name", list(product_dict.keys()))

        category = col3.text_input("Category")

        col4,col5,col6 = st.columns(3)

        quantity = col4.number_input("Quantity",min_value=1)
        warehouse = col5.selectbox("Warehouse",["A1","A2","B1","B2"])
        status = col6.selectbox("Status",["Draft","Waiting","Ready","Done","Cancelled"])

        receipt_date = st.date_input("Date",value=date.today())

        if st.button("Validate Receipt"):

            try:
                product_id = product_dict[product]

                query = """
                INSERT INTO receipts (supplier_name, product_id, quantity, warehouse, status)
                VALUES (%s, %s, %s, %s, %s)
                """

                cursor.execute(query, (supplier, product_id, quantity, warehouse, status))
                db.commit()

                new_row = pd.DataFrame([{
                "Supplier":supplier,
                "Product":product,
                "Category":category,
                "Quantity":quantity,
                "Warehouse":warehouse,
                "Status":status,
                "Date":receipt_date
                }])

                st.session_state.receipts = pd.concat(
                [st.session_state.receipts,new_row],
                ignore_index=True
                )

                if product in st.session_state.stock:
                    st.session_state.stock[product]+=quantity
                else:
                    st.session_state.stock[product]=quantity

                st.success("Receipt Added Successfully")

            except Exception as e:
                st.error(f"Database Error: {e}")

    # ---------------- RECEIPT HISTORY ----------------

    with tab2:

        st.subheader("Receipt History")

        query = """
        SELECT 
        r.receipt_id,
        r.supplier_name,
        p.product_name,
        r.quantity,
        r.warehouse,
        r.status,
        r.created_at
        FROM receipts r
        JOIN products p
        ON r.product_id = p.product_id
        ORDER BY r.receipt_id DESC
        """

        cursor.execute(query)
        data = cursor.fetchall()

        columns = [
            "Receipt ID",
            "Supplier",
            "Product",
            "Quantity",
            "Warehouse",
            "Status",
            "Date"
        ]

        df_receipts = pd.DataFrame(data, columns=columns)

        st.dataframe(df_receipts, use_container_width=True)

        if not df_receipts.empty:

            pdf_file = create_pdf(df_receipts)

            st.download_button(
                label="Download Receipt History PDF",
                data=pdf_file,
                file_name="receipt_history.pdf",
                mime="application/pdf"
            )

    # ---------------- STOCK TABLE ----------------

    with tab3:

        st.subheader("Current Stock")

        query = """
        SELECT 
        p.product_name,
        SUM(r.quantity) AS stock
        FROM receipts r
        JOIN products p
        ON r.product_id = p.product_id
        GROUP BY p.product_name
        """

        cursor.execute(query)
        data = cursor.fetchall()

        stock_df = pd.DataFrame(data, columns=["Product", "Stock"])

        if not stock_df.empty:
            st.dataframe(stock_df, use_container_width=True)
        else:
            st.info("No stock available yet")

    # ---------------- LEDGER ----------------

    with tab4:

        st.subheader("Stock Ledger")

        query = """
        SELECT 
        p.product_name,
        r.quantity,
        r.warehouse,
        r.created_at
        FROM receipts r
        JOIN products p
        ON r.product_id = p.product_id
        ORDER BY r.created_at DESC
        """

        cursor.execute(query)
        data = cursor.fetchall()

        ledger_df = pd.DataFrame(
            data,
            columns=["Product", "Quantity", "Warehouse", "Date"]
        )

        if not ledger_df.empty:

            ledger_df["Movement"] = "+" + ledger_df["Quantity"].astype(str)

            st.dataframe(
                ledger_df[["Product", "Movement", "Warehouse", "Date"]],
                use_container_width=True
            )

        else:
            st.info("No ledger entries")